stages:
  - lint
  - build
  - test
  - deploy

.eslint:
  stage: lint
  image: node:22-alpine
  script:
    - npm ci
    - npx eslint --format gitlab
  artifacts:
    reports:
      codequality: gl-codequality.json

build_website:
  stage: build
  image: node:22-alpine
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 4 weeks

test_artifacts:
  stage: test
  image: alpine
  script:
    - echo "🔍 Checking for index.html in build artifacts..."
    - |
      if [ -f build/index.html ]; then
        echo "✔ index.html is found."
      else
        echo "❌ index.html is not found."
        exit 1
      fi
  dependencies:
    - build_website

unit_test:
  stage: test
  image: node:22-alpine
  script:
    - npm ci
    - npm run test -- --reporter=junit --reporter=html
    - npm run test:report
  artifacts:
    paths:
      - reports/
    when: always
    reports:
      junit: reports/TEST-results.xml

netlify:
  stage: deploy
  image: node:22-alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install -g netlify-cli
    - apk add curl
  script:
    - netlify --version
    - netlify link --id "$NETLIFY_PROJECT_ID"
    - netlify status
    - echo "Authenticating Netlify CLI..."
    - netlify deploy --prod --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_PROJECT_ID" --dir=build --no-build
    - curl 'https://subash-nodejs-gitlab-cicd.netlify.app/' | grep GitLab
